# 错误和异常

>[错误和异常](https://docs.python.org/zh-cn/3.13/tutorial/errors.html)

如果您尝试过本教程前文中的例子，应该已经看到过一些错误信息。错误可（至少）被分为两种：*语法错误* 和 *异常*。

## 语法错误

语法错误又称解析错误，是学习 Python 时最常见的错误：

```python
while True print('Hello world')
  File "<stdin>", line 1
    while True print('Hello world')
               ^^^^^
SyntaxError: invalid syntax
```

解析器会重复出错的行并显示指向检测到错误的位置的小箭头。 请注意这并不一定是需要被修复的位置。 在这个例子中，错误在 [`print()`](https://docs.python.org/zh-cn/3.13/library/functions.html#print) 上被检测到，原因则是在它之前缺少一个冒号 (`':'`)。

将会打印文件名 (在我们的例子中为 `<stdin>`) 和行号以便你在输入是来自文件时能知道要去哪里查看。

## 异常

即使语句或表达式使用了正确的语法，执行时仍可能触发错误。执行时检测到的错误称为 *异常*，异常不一定导致严重的后果：很快我们就能学会如何处理 Python 的异常。大多数异常不会被程序处理，而是显示下列错误信息：

```python
10 * (1/0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
    10 * (1/0)
          ~^~
ZeroDivisionError: division by zero
4 + spam*3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
    4 + spam*3
        ^^^^
NameError: name 'spam' is not defined
'2' + 2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
    '2' + 2
    ~~~~^~~
TypeError: can only concatenate str (not "int") to str
```

错误信息的最后一行说明程序遇到了什么类型的错误。异常有不同的类型，而类型名称会作为错误信息的一部分中打印出来：上述示例中的异常类型依次是：[`ZeroDivisionError`](https://docs.python.org/zh-cn/3.13/library/exceptions.html#ZeroDivisionError)， [`NameError`](https://docs.python.org/zh-cn/3.13/library/exceptions.html#NameError) 和 [`TypeError`](https://docs.python.org/zh-cn/3.13/library/exceptions.html#TypeError)。作为异常类型打印的字符串是发生的内置异常的名称。对于所有内置异常都是如此，但对于用户定义的异常则不一定如此（虽然这种规范很有用）。标准的异常类型是内置的标识符（不是保留关键字）。

此行其余部分根据异常类型，结合出错原因，说明错误细节。

错误信息开头用堆栈回溯形式展示发生异常的语境。一般会列出源代码行的堆栈回溯；但不会显示从标准输入读取的行。

[内置异常](https://docs.python.org/zh-cn/3.13/library/exceptions.html#bltin-exceptions) 列出了内置异常及其含义。

## 异常的处理

可以编写程序处理选定的异常。下例会要求用户一直输入内容，直到输入有效的整数，但允许用户中断程序（使用 Control-C 或操作系统支持的其他操作）；注意，用户中断程序会触发 [`KeyboardInterrupt`](https://docs.python.org/zh-cn/3.13/library/exceptions.html#KeyboardInterrupt) 异常。

```python
while True:
    try:
        x = int(input("Please enter a number: "))
        break
    except ValueError:
        print("Oops!  That was no valid number.  Try again...")
```



[`try`](https://docs.python.org/zh-cn/3.13/reference/compound_stmts.html#try) 语句的工作原理如下：

- 首先，执行 *try 子句* （[`try`](https://docs.python.org/zh-cn/3.13/reference/compound_stmts.html#try) 和 [`except`](https://docs.python.org/zh-cn/3.13/reference/compound_stmts.html#except) 关键字之间的（多行）语句）。
- 如果没有触发异常，则跳过 *except 子句*，[`try`](https://docs.python.org/zh-cn/3.13/reference/compound_stmts.html#try) 语句执行完毕。
- 如果在执行 [`try`](https://docs.python.org/zh-cn/3.13/reference/compound_stmts.html#try) 子句时发生了异常，则跳过该子句中剩下的部分。 如果异常的类型与 [`except`](https://docs.python.org/zh-cn/3.13/reference/compound_stmts.html#except) 关键字后指定的异常相匹配，则会执行 *except 子句*，然后跳到 try/except 代码块之后继续执行。
- 如果发生的异常与 *except 子句* 中指定的异常不匹配，则它会被传递到外层的 [`try`](https://docs.python.org/zh-cn/3.13/reference/compound_stmts.html#try) 语句中；如果没有找到处理器，则它是一个 *未处理异常* 且执行将停止并输出一条错误消息。

[`try`](https://docs.python.org/zh-cn/3.13/reference/compound_stmts.html#try) 语句可以有多个 *except 子句* 来为不同的异常指定处理程序。 但最多只有一个处理程序会被执行。 处理程序只处理对应的 *try 子句* 中发生的异常，而不处理同一 `try` 语句内其他处理程序中的异常。 *except 子句* 可以用带圆括号的元组来指定多个异常，例如:

```python
... except (RuntimeError, TypeError, NameError):
...     pass
```

一个 [`except`](https://docs.python.org/zh-cn/3.13/reference/compound_stmts.html#except) 子句中的类匹配的异常将是该类本身的实例或其所派生的类的实例（但反过来则不可以 --- 列出派生类的 *except 子句* 不会匹配其基类的实例）。 例如，下面的代码将依次打印 B, C, D:

```python
class B(Exception):
    pass

class C(B):
    pass

class D(C):
    pass

for cls in [B, C, D]:
    try:
        raise cls()
    except D:
        print("D")
    except C:
        print("C")
    except B:
        print("B")
```

请注意如果颠倒 *except 子句* 的顺序（把 `except B` 放在最前），则会输出 B, B, B --- 即触发了第一个匹配的 *except 子句*。

发生异常时，它可能具有关联值，即异常 *参数* 。是否需要参数，以及参数的类型取决于异常的类型。

*except 子句* 可能会在异常名称后面指定一个变量。 这个变量将被绑定到异常实例，该实例通常会有一个存储参数的 `args` 属性。 为了方便起见，内置异常类型定义了 [`__str__()`](https://docs.python.org/zh-cn/3.13/reference/datamodel.html#object.__str__) 来打印所有参数而不必显式地访问 `.args`。

```python
try:
    raise Exception('spam', 'eggs')
except Exception as inst:
    print(type(inst))    # 异常的类型
    print(inst.args)     # 参数保存在 .args 中
    print(inst)          # __str__ 允许 args 被直接打印，
                         # 但可能在异常子类中被覆盖
    x, y = inst.args     # 解包 args
    print('x =', x)
    print('y =', y)

<class 'Exception'>
('spam', 'eggs')
('spam', 'eggs')
x = spam
y = eggs
```

未处理异常的 [`__str__()`](https://docs.python.org/zh-cn/3.13/reference/datamodel.html#object.__str__) 输出会被打印为该异常消息的最后部分 ('detail')。

[`BaseException`](https://docs.python.org/zh-cn/3.13/library/exceptions.html#BaseException) 是所有异常的共同基类。它的一个子类， [`Exception`](https://docs.python.org/zh-cn/3.13/library/exceptions.html#Exception) ，是所有非致命异常的基类。不是 [`Exception`](https://docs.python.org/zh-cn/3.13/library/exceptions.html#Exception) 的子类的异常通常不被处理，因为它们被用来指示程序应该终止。它们包括由 [`sys.exit()`](https://docs.python.org/zh-cn/3.13/library/sys.html#sys.exit) 引发的 [`SystemExit`](https://docs.python.org/zh-cn/3.13/library/exceptions.html#SystemExit) ，以及当用户希望中断程序时引发的 [`KeyboardInterrupt`](https://docs.python.org/zh-cn/3.13/library/exceptions.html#KeyboardInterrupt) 。

[`Exception`](https://docs.python.org/zh-cn/3.13/library/exceptions.html#Exception) 可以被用作通配符，捕获（几乎）一切。然而，好的做法是，尽可能具体地说明我们打算处理的异常类型，并允许任何意外的异常传播下去。

处理 [`Exception`](https://docs.python.org/zh-cn/3.13/library/exceptions.html#Exception) 最常见的模式是打印或记录异常，然后重新提出（允许调用者也处理异常）:

```python
import sys

try:
    f = open('myfile.txt')
    s = f.readline()
    i = int(s.strip())
except OSError as err:
    print("OS error:", err)
except ValueError:
    print("Could not convert data to an integer.")
except Exception as err:
    print(f"Unexpected {err=}, {type(err)=}")
    raise
```

[`try`](https://docs.python.org/zh-cn/3.13/reference/compound_stmts.html#try) ... [`except`](https://docs.python.org/zh-cn/3.13/reference/compound_stmts.html#except) 语句具有可选的 *else 子句*，该子句如果存在，它必须放在所有 *except 子句* 之后。 它适用于 *try 子句* 没有引发异常但又必须要执行的代码。 例如:

```python
for arg in sys.argv[1:]:
    try:
        f = open(arg, 'r')
    except OSError:
        print('cannot open', arg)
    else:
        print(arg, 'has', len(f.readlines()), 'lines')
        f.close()
```

使用 `else` 子句比向 [`try`](https://docs.python.org/zh-cn/3.13/reference/compound_stmts.html#try) 子句添加额外的代码要好，可以避免意外捕获非 `try` ... `except` 语句保护的代码触发的异常。

异常处理程序不仅会处理在 *try 子句* 中立刻发生的异常，还会处理在 *try 子句* 中调用（包括间接调用）的函数。 例如:

```python
def this_fails():
    x = 1/0

try:
    this_fails()
except ZeroDivisionError as err:
    print('Handling run-time error:', err)

Handling run-time error: division by zero
```



## 触发异常

[`raise`](https://docs.python.org/zh-cn/3.13/reference/simple_stmts.html#raise) 语句支持强制触发指定的异常。例如：

```python
raise NameError('HiThere')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
    raise NameError('HiThere')
NameError: HiThere
```

[`raise`](https://docs.python.org/zh-cn/3.13/reference/simple_stmts.html#raise) 唯一的参数就是要触发的异常。这个参数必须是异常实例或异常类（派生自 [`BaseException`](https://docs.python.org/zh-cn/3.13/library/exceptions.html#BaseException) 类，例如 [`Exception`](https://docs.python.org/zh-cn/3.13/library/exceptions.html#Exception) 或其子类）。如果传递的是异常类，将通过调用没有参数的构造函数来隐式实例化：

```python
raise ValueError  # 'raise ValueError()' 的简化
```

如果只想判断是否触发了异常，但并不打算处理该异常，则可以使用更简单的 [`raise`](https://docs.python.org/zh-cn/3.13/reference/simple_stmts.html#raise) 语句重新触发异常：

```python
try:
    raise NameError('HiThere')
except NameError:
    print('An exception flew by!')
    raise

An exception flew by!
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
    raise NameError('HiThere')
NameError: HiThere
```





